### ISSUE TITLE
Show rhythms on map

### ISSUE THREAD

**Issue by gregdyke** [ManSangSin/Rhythm-Code#1]
## Story

- **As a** website visitor

- **I Want** to view all rhythms on a map

- **So That** I can see how they are related in space

## Acceptance Criteria
 
1

   - Given 2 rhythms are hard coded, associated with Washington DC and Havana respectively
   - When site is visited at url [fill in here]
   - Then a map is displayed
   - And a small icon is shown for each rhythm on the map 

## PO notes
   - Any map can be used - first free map I found is https://www.cosmographics.co.uk/product/free-outline-map-of-north-america/
   - Icon can be any icon for now
   - No need to write anything next to the icon for now

## Implementation Notes

1. 
2.

## Checklist:

- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by mferryRV** [comment]
- [x] Create (or adapt) a page in React app
- [x] Research how to place things on a map (libraries we can use?)
- [x] Create a component for the map image (doesn't have to be final image)
- [x] Create an icon
- [x] Put the icon somewhere on the map (not even the right location yet)
- [x] Make the icon clickable
- [ ] Communicate all the data you need to make this happen (and make sure it's in a data model)
- [x] Finishing touches (placing the icon at the right point)
- [x] Make sure it works for more than one icon

Estimated 14 hours, ~3 evenings, so one week
