### ISSUE TITLE
Show rhythm codes

### ISSUE THREAD

**Issue by gregdyke** [ManSangSin/Rhythm-Code#16]
## Story

- **As a** website visitor

- **I Want** to be able to see only the rhythm codes ("parent codes to a set of related rhythm, e.g. the Blues rhythm code is parent to Struttin', Ballroomin', Piedmont triple")

- **So That** I'm not overwhelmed by the number of rhythms

## Acceptance Criteria

1. Given a rhythm code exists
   - When the map is shown
   - Then the rhythm code is included 
   - And it looks visually distinct from the rhythms (dot with surrounding circle?)
2. Given a rhythm code exists with "child" rhythms
   - When the rhythm code is clicked/selected
   - Then a small pane is dropped down, listing the child rhythms
3. Given a rhythm code pane is shown
   - When a rhythm is clicked
   - Then the modal for that rhythm is shown

## Implementation Notes

1.
2.

## Checklist:

- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by gregdyke** [comment]
<img width="286" alt="Screenshot 2023-09-29 at 18 02 06" src="https://github.com/ManSangSin/Rhythm-Code/assets/148489/846a47be-f912-48b9-bd8f-8554532431be">

**Comment by gregdyke** [comment]
No longer doing this stretch goal as we are not showing the rhythms on the map for now.

<s>Stretch goal: when a rhythm code is selected, highlight corresponding rhythms on the map</s>

**Comment by gregdyke** [comment]
Concern: isolated rhythms would not belong to a rhythm code -> for now, no isolated rhythms
How many rhythm codes shown at 1 time -> just one code can be selected at any one time

**Comment by mferryRV** [comment]
We need rhythm codes for DC hand dancing and Rumba Guaguanco in order to execute this effectively.

**Comment by gregdyke** [comment]
For now, I have for you:

Rhythm code: Rumba (location cuba/havana)
Rhythms: (all same location - for now, distribute them in a grid around Havana and we will clarify with Deirdre)
Rumba Columbiana https://www.youtube.com/watch?v=W4aMl4HpKIQ
Rumba Guaguanco (already in db)
Rumba Yambu https://www.youtube.com/watch?v=Mux8ibZWbrg
Rumba Habanera https://www.youtube.com/watch?v=iLGuLEqtq7g

**Comment by gregdyke** [comment]
lorem ipsem for now I'm afraid

**Comment by gregdyke** [comment]
As added in https://github.com/ManSangSin/Rhythm-Code/issues/22, we will stop showing rhythms as dots on the map and only show rhythm codes -> this could be done in this ticket, or separately

**Comment by mferryRV** [comment]
This is a prerequisite for #44 

We need to modify the data structure we use to focus on lists of Rhythm Codes rather than Rhythms. Currently `/apis/rhythms` returns a list of rhythms. We either need an API endpoint for a list of rhythm codes and their child rhythms OR the front-end needs to group rhythms by rhythm code.
