### ISSUE TITLE
Show rhythm codes instead of rhythms

### ISSUE THREAD

**Issue by gregdyke** [ManSangSin/Rhythm-Code#22]
## Story

- **As a** PO

- **I Want** to only see rhythm codes on the map

- **So That** we postpone solving the problem of rhythms that are not co-located with their rhythm code until after the project is finished

## Acceptance Criteria

1. Given there is rhythm and rhythm code data fetched from the backed
   - When the map is shown
   - Then only rhythm codes are shown

## Implementation Notes

1.
2.

## Checklist:

- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by mferryRV** [comment]
Similar to #6 it would be helpful to have a prototype for the UX and UI expected, even if it is basic.

**Comment by gregdyke** [comment]
Sorry for the change in functionality for this

**Comment by mferryRV** [comment]
Sorry for changing the name here, we kept losing it! This is an important one.

Tied with #16 and #44

**Comment by mferryRV** [comment]
@rogerspooner - can you determine if this is a duplicate of #16?

**Comment by rogerspooner** [comment]
Duplicate of #16. Closing
