### ISSUE TITLE
Nice User Interface

### ISSUE THREAD

**Issue by justinchensd** [ManSangSin/Rhythm-Code#32]
## Story

- **As a** visitor

- **I Want** to see an appealing website

- **So That** I can interact with the website and get the information in a convenient way.

## Acceptance Criteria

1. Given .............
   - When .............
   - Then .............
2. Given .............
   - When .............
   - Then .............

## Implementation Notes

1. Please add CSS and other useful information for this website
2.

## Checklist:

- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by mferryRV** [comment]
Close as this is high-level and other tickets cover low level
