### ISSUE TITLE
Styling the page - Container

### ISSUE THREAD

**Issue by justinchensd** [ManSangSin/Rhythm-Code#37]
Please add a container to display all of the sections on the page.

**Comment by mferryRV** [comment]
We will be updating the UI of our application to match [this Figma design](https://www.figma.com/file/2N8IdMbPkQnl0MT6gERTvc/CYF-Rhythm-Code?type=design&node-id=70%3A60&mode=design&t=gxOy2POOpK2XBygT-1) on page "Prototype web".

To accomplish this, we need to wrap our Home page component in a div with the following stylistic requirements:
* Flexbox: true
* Max width: 1440px
* Font: Roboto

We will also need to import Roboto and Oswald fonts by adding `<link>` elements to the `<head>` section of the HTML file.

This will allow the components inside to fit the shape we expect in our designs. To understand flexbox, play [Flexbox Froggy](https://flexboxfroggy.com/).

This design is desktop-first, so we will review mobile designs later in the week.

**Comment by mferryRV** [comment]
Oswald font: https://fonts.google.com/specimen/Oswald
Roboto font: https://fonts.google.com/specimen/Roboto
