### ISSUE TITLE
Get rhythm data from backend

### ISSUE THREAD

**Issue by gregdyke** [ManSangSin/Rhythm-Code#4]
## Technical task

This fulfills that the hardcoding of the rhythm data happens during seeding of the db, instead of on the frontend - it is preparation for ability to add new rhythms and have them show up.

## Acceptance Criteria

1. Given data is present on the backend
   - When http request is sent: GET /[fill in endpoint here]
   - Then json in format [fill in here] is returned
2. Given data is present on the backend and a GET endpoint exists
   - When the user goes to the map page (see issue xxxx)
   - Then the data that is displayed is the data that comes from the backend

## Implementation Notes

1. Probably split up into ticket with dependency on the map and ticket without dependency:
  - no dependency: API endpoint + fetch that console.logs the result
  - dependency: fetch passes data to map component (or is fetched from map component)

## Checklist:

- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by mferryRV** [comment]
Needs:
- [x] ~Need a database~ - hardcode it
- [x] Need a JSON structure for the response: https://codeyourfuture.slack.com/archives/C05SUQ3K5DY/p1695482094908699
- [x] Need to define how many requests and what type - one request returns all the rhythms and all the information about the rhythms

Tasks

- [x] Name the endpoint 
- [x] Create a GET endpoint
- [x] Return the JSON data - list of all rhythms and their information
- [x] Create a data fetching test page
- [x] Fetch data from backend
- [x] Console log the data on the frontend
