### ISSUE TITLE
Styling the page - About

### ISSUE THREAD

**Issue by justinchensd** [ManSangSin/Rhythm-Code#40]
image  title content

**Comment by mferryRV** [comment]
We will be updating the UI of our application to match [this Figma design](https://www.figma.com/file/2N8IdMbPkQnl0MT6gERTvc/CYF-Rhythm-Code?type=design&node-id=70%3A60&mode=design&t=gxOy2POOpK2XBygT-1) on page "Prototype web".

<img width="974" alt="image" src="https://github.com/ManSangSin/Rhythm-Code/assets/24232245/582e5ea0-4bd5-4601-ba1b-1f90bb3ab1ee">

To accomplish this, we need to create a `<AboutSection>` component and add it to our Home page component. This About Section should have:

- A black background
- The title in Roboto Bold 32, white
- Body content in Roboto Regular 16
- The image (download from Figma)
- [Flexbox](https://flexboxfroggy.com/) styling

To see the styling information for the page, activate Figma's Dev Mode in the top righthand corner:
![image](https://github.com/ManSangSin/Rhythm-Code/assets/24232245/4efc29a9-d545-4a25-8210-8aeb75746796)

This design is desktop-first, so we will review mobile designs later in the week.

**Comment by rogerspooner** [comment]
@gregdyke , you or perhaps I should get the actual text from Derdrie. Also the image. Currently the text is Lorem ispum.

**Comment by mferryRV** [comment]
1 day + feedback (1.5 days)
