### ISSUE TITLE
Styling the page - map - locations and rhythm codes

### ISSUE THREAD

**Issue by justinchensd** [ManSangSin/Rhythm-Code#44]
icon, rhythm code, rhythm list, clickable rhythms

When the mouse hovers over the location icon, the rhythm code and list should appear.
When the rhythm is clicked, the modal will be displayed.

**Comment by mferryRV** [comment]
NOTE: This issue may be dependent on #16 and #22

We will be updating the UI of our application to match [this Figma design](https://www.figma.com/file/2N8IdMbPkQnl0MT6gERTvc/CYF-Rhythm-Code?type=design&node-id=70%3A60&mode=design&t=gxOy2POOpK2XBygT-1) on page "Prototype web".

<img width="808" alt="image" src="https://github.com/ManSangSin/Rhythm-Code/assets/24232245/59d1ec9c-f0b7-4a79-8273-992ef5d32284">

To accomplish this, we need to modify our MapIcon components to represent Rhythm Codes and their Rhythms. The visual icon should have:

- An icon (download from Figma)
- The rhythm code in Roboto Bold 16, #CB3100
- A list of rhythms in Roboto Regular 16, #CB3100
- [Flexbox](https://flexboxfroggy.com/) styling

To see the styling information for the page, activate Figma's Dev Mode in the top righthand corner:
![image](https://github.com/ManSangSin/Rhythm-Code/assets/24232245/4efc29a9-d545-4a25-8210-8aeb75746796)

This design is desktop-first, so we will review mobile designs later in the week.
